language: java

jdk:
  - oraclejdk14

sudo: false

cache:
  directories:
    - $HOME/.m2

## export GPG details
## Running command to get secret key in base64 format:
## gpg -a --export-secret-keys <your-email-address> | base64 -w 0
## Running command to get ownertrust in base64 format:
## gpg --export-ownertrust | base64 -w 0
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

## Build and release to maven central
script:
  mvn --settings .travis.settings.xml clean deploy -B -U -Prelease

after_success:
  - bash <(curl -s https://codecov.io/bash)

## Get the project version
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: W+ghjW3DbFj6iDcOR/yrbZQ+MSNSypWm9/In5Krh6i5RduFeb6q7SwGFmmRwmb5jbINk9IgyvYPJWJvVuixYmy0rAdp8n1HRBvNNcXpUvVLjNxgsbviyvYpRvQs/EtCyRbKmsjvdcKTNy16kswRIEUoCWPJ3lDYMfjrlrpiGVrtyvOJd0CXaZnLlxQ2TW0IRR/6w6HFvufDldI6jsQ4Cqh9wuTXD4FxJu17flDUl3DEBuMfoAiKqHy0viiKHWveb/GZDtF4FmGN3d1sFOkPyzmf3u3kJOZhOVDhE59/9EmhTwLexvSjv57NGSylH8xhB6Gj7RPHcHQ0dCB63UDMsItBxRsz9KaA2z5GSaNrvAmx3wk0v/uw0RHNg5LGV+n/o1tLk1LnNGzcvQT+B+JAIZWlozMPe9AXV/MeHkMn6LLfwD92J+mp8k+ztnhaAetgoZOgfmwefm3AP0nHBL3siLyDUeQDtbVemtkoOLRRtgY8E7lqAqjXXwWboOMOQzEu+5S1UwO8QfZE/rPjOKN+vuLvgWjv2zSXYYXwWVjZCLnwLozExPhXxJvV8M3JpYveE3gfAEIndW8WPEMs+KdCCGNbRFi3DbPkoEdEoYGlRkxDuu6CSntf/LfNidJoyaI+NbSEDOr9AKh/6pQMbzWmIENvJIVB9J3UpSEHh2RW/E9E=
  file:
    - unique-file-name-generator-$project_version.jar
    - unique-file-name-generator-$project_version-javadoc.jar
    - unique-file-name-generator-$project_version-sources.jar
  on:
    repo: DEARaison/unique-file-name-generator
  skip_cleanup: 'true'
  name: Version $project_version
