language: java
jdk:
  - oraclejdk14
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
script:
  mvn --settings .travis.settings.xml clean deploy -B -U -Prelease
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  - git config --local user.name "DEARaison"
  - git config --local user.email "mrbaotruongit@gmail.com"
  - git tag v$project_version
deploy:
  provider: releases
  api_key:
    secure: hum7eIkozK0gT7YyK5+k0dYi7Ei0/227Z3TmWybD2Q7706fOIKZ8k1zSTqnWofbKitrcgbUCtGB4N3mZzSPNEHoNiNPiypHwm4z6A+FnwpptyQDDYk/zHDT3e284KhplwjeHrmdTsoRolOgnXLhO+QgzTsL3xKwG6C08UNNu6zaZ+wjBxMvkQerTD2FlSlvakyb4aTmCZgaASzQkM7IoFfmkbY0bShBD0DqBih8Pp50md/wsUgkqZExpB4f9Z4QU8Ov1F4Su3DfSx67UZa9KUGvGxFPKCCMRAG7zECPvxrMhgrOqYD1l8tT7IRxdGenhLVEhvEPaEtSMXPq0N2N31yR0iS0PTtUYLo8vrtI3uD1Larn/E2618z+51eg0wcxAauQmDujt4zjBfOaqv42vJVnYuZRubx7Ekp/2lhEbMpj06D1/AmGiquBhxUuWtbAGTcy7otx3W0gpSYtlV9Zd+j9d6XUXdnkYtN1tXEMJS3PTAlnM3Gq7UoI6B8vMEkYeHRbMCf3+4ZKF/K+Vg2XZRmTGG18IRZjJwE5P7H9lFfBZEvKHwrgmk0B2FurW1PPFCNwZY93XkpYAFg5FPviF357NohknelZGMQZrDVNyqPHa7I99TfMh1liQCJhUCDhKI3vLcUi7vsAFfKPxHzMjKJVEhCBiKj3gEYmuJ6DknXo=
  file:
    - target/unique-file-name-generator-$project_version.jar
    - target/unique-file-name-generator-$project_version-javadoc.jar
    - target/unique-file-name-generator-$project_version-sources.jar
  on:
    repo: DEARaison/unique-file-name-generator
  skip_cleanup: 'true'
  name: Version $project_version
